---
apiVersion: v1
kind: Namespace
metadata:
  name: websrv-lesson-12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: websrv-lesson-12
  labels:
    app: nginx-websrv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-websrv
  template:
    metadata:
      labels:
        app: nginx-websrv
    spec:
      containers:
      - name: nginx-instance
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: index-html-mount
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: index-html-mount
        configMap:
          name: index-html-custom-data
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  namespace: websrv-lesson-12 
 labels:
    run: nginx-web-service
spec:
#  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx-websrv
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: websrv-lesson-12
  name: ingress-sa
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "app.k8s-1.sa"
spec:
  rules:
    - host: app.k8s-1.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-web-service
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: websrv-lesson-12
  name: index-html-custom-data
data:
  index.html: |
    <html>
          <header><title>Custom index.html</title></header>
          <body>Custom test page!!!</body>
    </html>
