apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-external
  namespace: wordpress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "wordpress.k8s-2.sa"
spec:
  rules:
    - host: wordpress.k8s-1.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
